twiterfluence/app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True, index=True)
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    def __repr__(self):
        return f'User {self.username}'

twiterfluence/app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail
from flask_moment import Moment
from TwitterAPI import TwitterAPI
from flask_dance.contrib.twitter import make_twitter_blueprint, twitter


bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
photos = UploadSet('photos', IMAGES)
mail = Mail()
moment = Moment()



def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations.
    app.config.from_object(config_options[config_name])

    # Intitializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    moment.init_app(app)
    login_manager.session_protection = 'strong'
    login_manager.login_view = 'auth.login'
    # configure upload setUp
    configure_uploads(app, photos)
    mail.init_app(app)
    # Registering the blueprint

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    twitter_blueprint = make_twitter_blueprint(api_key="AQiZnAVb1NlnMJooyIYonMiO8",api_secret="l08BAtgpJjOnblfJYxOK5gip2XSbQCNhsg7vNj9zcgmdLg2t3J")

    app.register_blueprint(twitter_blueprint, url_prefix="/login")

    return app

twiterfluence/app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import errors, forms, views

twiterfluence/app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from ..models import User
from .. import db
from flask_login import login_user, logout_user, login_required, current_user
from ..email import mail_message
from datetime import datetime, date
from dateutil.relativedelta import relativedelta
from dateutil import rrule
from TwitterAPI import TwitterAPI
import json
from flask_dance.contrib.twitter import make_twitter_blueprint, twitter
import time
from time import mktime
import math




@main.route('/')
def index():
    """View root page function that returns index page and the various news sources"""

    title = 'Home- Welcome to Twitfluence'

    return render_template('index.html', title=title)

# @main.route('/twitter/authorized')
# def twitter_login():
#     if not twitter.authorized:
#         return redirect(url_for('twitter.login'))
#     resp = twitter.get("account/settings.json")
#     assert resp.ok
#
#     return render_template('search.html')

@main.route('/search', methods=['GET', 'POST'])
def search_user():
    consumer_key ='AQiZnAVb1NlnMJooyIYonMiO8'
    consumer_secret ='l08BAtgpJjOnblfJYxOK5gip2XSbQCNhsg7vNj9zcgmdLg2t3J'
    access_token='300098394-Ip8cNXKnD6bsaXFSbPXwhsFWrKDvo9gQdXkuhNcK'
    access_token_secret='OQtSOnKHxIf0UpACvrCsKazWBYdFCP4dCXZqnjoJXxPF6'
    api = TwitterAPI(consumer_key, consumer_secret, access_token, access_token_secret)

    user_name = request.args.get('screen_name')

    if user_name is None:
        user_name = 'twitterdev'
    payload={'screen_name':user_name}
    r = api.request('users/lookup', params=payload)
    info = r.json()[0]

    date_created = info['created_at']
    date_created_time_struct = time.strptime(date_created, '%a %b %d %H:%M:%S %z %Y')
    date_created_date = datetime.fromtimestamp(mktime(date_created_time_struct)).date()
    date_now=datetime.now().date()
    delta = date_now - date_created_date
    number_of_days = delta.days
    number_of_tweets = info['statuses_count']
    number_of_followers = info['followers_count']
    number_of_following = info['friends_count']

    def twitfluence(tweets, days, followers, following):
        first=math.log((tweets/days)*followers*(math.log(((followers/following)+1),10)), 10)
        if first > 10:
            return 10
        if first < 0:
            return 0.1
        return first

    twitfluence_score = twitfluence(number_of_tweets,number_of_days, number_of_followers, number_of_following)
    percentage_score = math.floor(twitfluence_score*10)

    trends = api.request('trends/place', 'id=1528488').json()[0]['trends']

    print(trends[0])


    return render_template('search.html', info=info, percentage_score=percentage_score, trends =trends)

twiterfluence/app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!DOCTYPE html>
<html>

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Home- Welcome to Twitfluence</title>
    {% endif %}

  </head>

  <body>
    <!-- Content Block -->
    {% block content %} {% endblock %}
    <!-- Navbar block  -->
    {% block navbar %} {% include 'navbar.html' %} {% endblock %}
    {% block scripts%}
        {{super()}}
      {{ moment.include_jquery() }}
      {{ moment.include_moment() }}
      <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    {% endblock %}
  </body>

</html>

twiterfluence/app/templates/index.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block content %}
<div class="container-fluid" style="background-image:url('static/images/faces-2679755_1280.jpg'); background-size:cover; position:fixed; height:100%; width:100%">
  <div class="row">
    <div class="col-md-4">

    </div>
    <div class="col-md-4" style="margin-top:10%">
      <div class="well" style="height:100%; opacity:0.9; width:100%">
        <a href="{{ url_for('main.index') }}"><h2 class="text-center text-primary" style="font-family: 'Bree Serif', serif;">TWIT-FLUENCE</h2></a>
        <div class="buttons" style="margin-top:50%">
          <a href="{{url_for('auth.login')}}">
          <button type="click" name="button" class="btn btn-default btn-block" id="sign-in">SIGN IN</button>
          </a>
          <a href="{{url_for('auth.register')}}">
          <button type="button" name="button" class="btn btn-default btn-block" id="register">REGISTER</button>
        </a>
        <a href="{{url_for('twitter.login')}}">
        <button type="button" name="button" class="btn btn-default btn-block" id="register">LOG IN WITH TWITTER</button>
      </a>
        </div>
      </div>
    </div>
      <div class="col-md-4">
      </div>
  </div>
  {% endblock %}{% block styles%} {{ super() }}
<link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet">  <style>
    /*font-family: 'Courgette', cursive;
font-family: 'Sedgwick Ave Display', cursive;
font-family: 'Lobster', cursive;
font-family: 'Yanone Kaffeesatz', sans-serif;
font-family: 'Bree Serif', serif;
font-family: 'Acme', sans-serif;
font-family: 'Berkshire Swash', cursive;*/

    * {
      box-sizing: border-box;
    }

    h1 {
      font-family: 'Berkshire Swash', cursive;
      font-weight: 400;
      font-style: italic;
      font-size: 3.5em;
      margin-top: 10%;
    }

    h2 {
      font-family: 'Berkshire Swash', cursive;
      font-weight: 400;
      font-size: 2.5em;
    }

    p {
      font-size: 20px;
    }

    .container-fluid {
      background-color: #2471A3;
    }
    #register{
      margin-top: 20px;
    }
  </style>
  {% endblock %}

twiterfluence/app/templates/navbar.html
<nav class="navbar navbar-inverse" style="background-color:#1B4F72 ">
  <div class="container-fluid">
    {% if current_user.is_authenticated %}
    <div class="navbar-header">
      <a class="navbar-brand" href="{{ url_for('main.search_user') }}">TWIT-FLUENCE</a>
    </div>
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{{url_for('main.search_user')}}"><span class="glyphicon glyphicon-user"></span> MY PROFILE</a></li>
      <li><a href="{{url_for('auth.logout')}}"><span class="glyphicon glyphicon-log-out"></span> LOG OUT </a></li>
    </ul>
    {% endif %}

  </div>
</nav>

twiterfluence/app/templates/search.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="col-xs-5">
    <form style="width:400px">
      <input type="text" name="screen_name" placeholder="Search for a user" class="form-control" value={{user_name}}>
      <input type="submit" value="SEARCH" class="btn btn-default btn-block ">
    </form>
    <div class="portfoliocard">
      <div class="coverphoto" style="background-image: url('{{info['profile_banner_url']}}');"></div>
      <div class="profile_picture" style="background-image: url('{{info['profile_image_url_https']}}')"></div>
      <div class="left_col">
        <div class="followers">
          <div class="follow_count">{{info['followers_count']}}</div>
          Followers
        </div>
        <div class="following">
          <div class="follow_count">{{info['friends_count']}}</div>
          Following
        </div>
        <div class="following">
          <div class="follow_count">{{info['statuses_count']}}</div>
          Tweets
        </div>
      </div>
      <div class="right_col">
        <h2 class="name">{{info['name']}}</h2>
        <a href="{{info['url']}}"><h3 class="location">@{{info['screen_name']}}</h3></a>
        <div class="progress-pie-chart" data-percent="{{percentage_score}}">

          <div class="ppc-progress">
            <div class="ppc-progress-fill"></div>
          </div>
          <div class="ppc-percents">
            <div class="pcc-percents-wrapper">
              <span>%</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-3">

  </div>
  <div class="col-xs-4">
    <div class="span4">
      <div class="todo mrm">
        <div class="todo-header">
          <h3 class="demo-panel-title">Trending Topics</h3>
        </div>
        <ul style="overflow-y:scroll; height:470px">
          <li class="todo-wrap one">
            <div class="todo-content">
              <h4 class="todo-name text-center">
                  Kenya
                </h4>
              <ul>
                {% for trend in trends%}
                <a href="{{trend['url']}}" style="text-decoration:none">
                  <div class="trends">
                    <li style="margin-top:10px">{{trend['name']}}</li>
                    <hr>
                  </div>
                </a>
                {% endfor %}
              </ul>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>


{% block scripts %} {{super()}}
<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>


<script type="text/javascript">
  $(function() {
    var $ppc = $('.progress-pie-chart'),
      percent = parseInt($ppc.data('percent')),
      deg = 360 * percent / 100;
    if (percent > 50) {
      $ppc.addClass('gt-50');
    }
    $('.ppc-progress-fill').css('transform', 'rotate(' + deg + 'deg)');
    $('.ppc-percents span').html(percent + '%');
  });
</script>

{% endblock %} {% endblock %} {% block styles %} {{ super() }}
<link rel="stylesheet" href="{{url_for('static', filename = 'css/search.css')}}">
{% endblock %}